module.exports = [
  'propositional logic',
  'predicate logic',
  'first-order logic',
  'set theory',
  'graph theory',
  'combinatorics',
  'number theory',
  'boolean algebra',
  'formal languages',
  'finite automata',
  'recurrence relations',
  'tree structures',
  'algorithm analysis',
  'combinatorial optimization',
  'discrete structures',
  'logic circuits',
  'proof techniques',
  'cryptographic protocols',
  'game theory',
  'information theory',
  'linear algebra',
  'matroid theory',
  'network flows',
  'poset theory',
  'queueing theory',
  'group theory',
  'ring theory',
  'field theory',
  'lattice theory',
  'modal logic',
  'topology',
  'computability theory',
  'lambda calculus',
  'category theory',
  'probability theory',
  'finite model theory',
  'hypergraph theory',
  'ramsey theory',
  'turing machines',
  'graph algorithms',
  'discrete optimization',
  'enumerative combinatorics',
  'formal methods',
  'information retrieval',
  'coding theory',
  'design theory',
  'combinatorial geometry',
  'universal algebra',
  'mathematical logic',
  'arithmetical logic',
  'structural induction',
];
